default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV['SQL_USER'] %>
  password: <%= ENV['SQL_PASSWORD'] %>

test:
  <<: *default
  username: <%= ENV['SQL_USER'] %>
  password: <%= ENV['SQL_PASSWORD'] %>

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>